// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import AlertsController from "./alerts_controller"
application.register("alerts", AlertsController)

// Selecting elements
const allSections = document.querySelectorAll('section');
const allButtons = document.getElementsByTagName('button');


// Smoot scroling

const btnScrollTo = document.querySelector('.btn--scrole-to');
const homeSection = document.querySelector('.header');
const portfolioSection = document.querySelector('#portfolio-section')

btnScrollTo.addEventListener('click', function (e) {

  const s1coords = homeSection.getBoundingClientRect();

  // Old way
    window.scrollTo({
    left: s1coords.left + window.pageXOffset,
    top: s1coords.top + window.pageXOffset,
    behavior: 'smooth',
  });

  // // new way
  // btn = portfolioSection.scrollIntoView({ beavior: 'smooth' });
  // console.log("hello from portfolio button");
})
